import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "PDF Extractor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-custom-font-family">
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
